apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: white-whale
  targetCPUUtilizationPercentage: 40