apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: white-whale
  annotations:
    kubernetes.io/ingress.class: contour
    external-dns.alpha.kubernetes.io/target: contour.white-whale.net
spec:
  virtualhost:
    fqdn: app.k8s-west1.white-whale.net
  routes:
  - timeoutPolicy:
      response: 60s
      idle: 20s
    services:
    - name: svc
      port: 8333