apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: white-whale
commonLabels:
  app: white-whale
  env: dev
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - httpproxy.yaml