apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports:
  - name: bitcoin
    port: 8333
    protocol: TCP
    targetPort: 8333
  selector:
    active: "true"
    app: white-whale
  type: ClusterIP
